providerInfo: HelloWorld
server:
  port: 8013
spring:
  application:
    name: UserProvider
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-day03?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka,http://localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true
