provider-Info: HelloWorld---UserProvider2!
server:
  port: 8014
spring:
  application:
    name: UserProvider
  datasource:
    url: jdbc:mysql://db1:3306/jpa-last?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka,http://localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true
